name: Terraform Plan
description: Runs a terraform plan for the given environment

inputs:
  environment:
    required: true
    description: Environment name
  google_client_id:
    required: true
    description: Google OAuth client ID
  google_client_secret:
    required: true
    description: Google OAuth client secret

runs:
  using: composite
  steps:
    - name: Plan
      shell: bash
      env:
          TF_VAR_google_client_id: ${{ inputs.google_client_id }}
          TF_VAR_google_client_secret: ${{ inputs.google_client_secret }}
          # TF_VAR_facebook_app_id: ${{ secrets.FACEBOOK_APP_ID }} --- NOT NECESSARY FOR MVP, COMMENTING OUT FOR NOW ---
          # TF_VAR_facebook_app_secret: ${{ secrets.FACEBOOK_APP_SECRET }} --- NOT NECESSARY FOR MVP, COMMENTING OUT FOR NOW ---
      run: |
        terraform plan -var-file="${{ inputs.environment }}.tfvars"
