name: Dev Terraform CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    uses: ./.github/workflows/reusable_cicd.yml
    permissions:
      id-token: write
      contents: read

    with:
      working_directory: .
      environment: dev
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN_DEV }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
