name: Prod Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/reusable_cicd.yml
    permissions:
      id-token: write
      contents: read
      
    with:
      working_directory: .
      environment: prod
    secrets:
      OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      ORIGIN_PUBLISHABLE_KEY: ${{ secrets.PUBLISHABLE_KEY }}
      ORIGIN_SECRET_KEY: ${{ secrets.SECRET_KEY }}
